CloudExperienceWeb/Controllers/CloudObserverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using CloudObserver;

namespace CloudExperienceWeb.Controllers
{
    public class CloudObserverController : Controller
    {
        public ActionResult Index()
        {
            //var context = new CloudObserverDB();
            //var observations = from at in context.Observations  select new  { City = at.City, CameraId = at.CameraId, Lat = at.Lat, Long = at.Long, ObservationTimeStamp = at.ObservationTimeStamp, ImageTimeStamp = at.ImageTimeStamp };
            //ViewBag.Observations = observations.ToList().Select(o => new CloudObservation { City = o.City, CameraId = o.CameraId, Lat = o.Lat, Long = o.Long,ObservationTimeStamp = o.ObservationTimeStamp, ImageTimeStamp = o.ImageTimeStamp });

            return View();
        }

        public ActionResult GridData(string sidx, string sord, int page, int rows)
        {
            //var context = new CloudObserverDB();
            //var observations = from at in context.Observations select new { City = at.City, CameraId = at.CameraId, Lat = at.Lat, Long = at.Long, ObservationTimeStamp = at.ObservationTimeStamp, ImageTimeStamp = at.ImageTimeStamp };
           // ViewBag.Observations = observations.ToList().Select(o => new CloudObservation { City = o.City, CameraId = o.CameraId, Lat = o.Lat, Long = o.Long, ObservationTimeStamp = o.ObservationTimeStamp, ImageTimeStamp = o.ImageTimeStamp });

            return View();
       
        }
    }
}

CloudExperienceWeb/Controllers/CloudSpotterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Xml;
using System.Text;

namespace CloudExperienceWeb.Controllers
{
    public class CloudSpotterController : Controller
    {
        //
        // GET: /CloudSpotter/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Spot(string query,int noCams = 40)
        {
            string url = "http://api.wunderground.com/auto/wui/geo/GeoLookupXML/index.xml?query="+ query;

            // Create an interface to the web
            WebClient c = new WebClient();
            // Download the XML into a string
            string xml = ASCIIEncoding.Default.GetString(c.DownloadData(url));
            // Document to contain the feed
            XmlDocument doc = new XmlDocument();
            // Parse the xml
            doc.LoadXml(xml);

            string cams = string.Empty;
            // Display each cam
            List<Tuple<string,string>> camList = new List<Tuple<string,string>>();
            foreach (XmlNode node in doc.SelectNodes("/location/webcams/cam"))
            {
                string location = node.SelectSingleNode("city").InnerText;
                string imgUrl = node.SelectSingleNode("CURRENTIMAGEURL").InnerText;


                camList.Add(new Tuple<string, string>(imgUrl,location));

                if (camList.Count >= noCams) break;
            }

            ViewBag.Message = camList.Count.ToString() + " cams spotted";
            ViewBag.URLs = camList;

            return View();
        }
    }
}

CloudExperienceWeb/Controllers/CloudVideoManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Diagnostics;
using Microsoft.WindowsAzure.ServiceRuntime;
using Microsoft.WindowsAzure.StorageClient;
//using CloudVideoRenderer;
//using CloudObserver;

namespace CloudExperienceWeb.Controllers
{
    public class CloudVideoManagerController : Controller
    {
        //
        // GET: /CloudVideoManager/

        public ActionResult Index()
        {
            List<string> frameRates = new List<string>();
            frameRates.Add("10");
            frameRates.Add("15");
            frameRates.Add("20");
            frameRates.Add("25");
            frameRates.Add("30");

            ViewData["frameRate"] = new SelectList(frameRates);

            ////var context = new CloudObserverDB();


            //var cameraIds = (from p in context.Observations
            //                 select p.CameraId).Distinct();

            //List<string> cameraIdList = new List<string>();

            //foreach (string s in cameraIds)
            //{
            //    cameraIdList.Add(s);
            //}

            //ViewData["cameraIdList"] = new SelectList(cameraIdList);


            //Video links:
            CloudBlobClient blobClient = new CloudBlobClient("http://cloudexperience.blob.core.windows.net/", new StorageCredentialsAccountAndKey("cloudexperience", "2gXf57tBwJq7MRTi9WkcPuTNdz66Ra7hD4BNIDGpv/ztlT+juvw2886rL8CYmWwRFwQUhNOBVAU67Rea3Cpnaw=="));
            //Get a reference to a container, which may or may not exist.
            CloudBlobContainer container = blobClient.GetContainerReference("cloudvideo");

            List<string> videoList = new List<string>();

            IEnumerable<IListBlobItem> blobList = container.ListBlobs();
            foreach (IListBlobItem item in blobList)
            {
                videoList.Add(item.Uri.AbsoluteUri.ToString());
            }

            ViewBag.VideoList = new SelectList(videoList);

            return View();
        }

        public ActionResult HandleForm(string cameraIdList, string frameRate, bool renderAll, string pass)
        {
            string response = string.Empty;
            CloudStorageAccount account = CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=cloudexperience;AccountKey=2gXf57tBwJq7MRTi9WkcPuTNdz66Ra7hD4BNIDGpv/ztlT+juvw2886rL8CYmWwRFwQUhNOBVAU67Rea3Cpnaw==");
            CloudQueueClient queueClient = account.CreateCloudQueueClient();
            CloudQueue renderJobQueue = queueClient.GetQueueReference("renderjobqueue");

            if (!renderJobQueue.Exists())
            {
                renderJobQueue.Create();
            }

            if (renderAll && pass == "cexp")
            {
                //var context = new CloudObserverDB();
                //var cameraIds = (from p in context.Observations
                //                 select p.CameraId).Distinct();


                //foreach (string s in cameraIds)
                //{
                //    CloudVideoRenderJob job = new CloudVideoRenderJob { CameraID = s, CloudVideoRenderJobId = Guid.NewGuid().ToString(), FrameRate = int.Parse(frameRate) };
                //    CloudQueueMessage message = new CloudQueueMessage(MessageSerializer.Serialize(job));
                //    renderJobQueue.AddMessage(message);

                //    response += job.CameraID + " - ";
                //}
            }
            else
            {
                //CloudVideoRenderJob job = new CloudVideoRenderJob { CameraID = cameraIdList, CloudVideoRenderJobId = Guid.NewGuid().ToString(), FrameRate = int.Parse(frameRate) };
                //CloudQueueMessage message = new CloudQueueMessage(MessageSerializer.Serialize(job));
                //renderJobQueue.AddMessage(message);

                //response = job.CameraID;
            }


            ViewBag.JobId = response;

            return View();
        }

    }
}

CloudExperienceWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/jquery.jqGrid/ui.jqgrid.css")" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")" type="text/javascript"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jcarousellite_1.0.1.js")"></script>
</head>
<body  bgproperties="fixed">
    <div class="page">
        <header>
            <div id="title">
                <img width="250" src="../../Content/logo.png" />
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Start", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cloud spotter", "Spot", "CloudSpotter", new { query = "eindhoven", noCams = 50 }, null)</li>
                    <li>@Html.ActionLink("Cloud observer", "Index", "CloudObserver")</li>
                    <li>@Html.ActionLink("Cloud video manager", "Index", "CloudVideoManager")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>


</body>
</html>

CloudExperienceWeb/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}